import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Selector } from '../components/Selector.tsx';
import { KeyProvider } from '../context/main-context.tsx';
import { Key, Progression } from "@tonaljs/tonal";

const Home: NextPage = () => {

  return (
      <KeyProvider>
    <div className={styles.container}>
      <Head>
        <title>Nashville Numbers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://en.wikipedia.org/wiki/Nashville_Number_System">The Nashville Numbers Game</a>
        </h1>

      <Selector/>
        <div>
          {/*{harmonicFunctionGroups.T.map((el) => {
            return <p key={el}>{el}</p>;
          })}
        </div>

        <div>
          <h2> SubDominant </h2>
          {harmonicFunctionGroups.SD.map((el) => {
            return <p key={el}>{el}</p>;
          })}
        </div>

        <div>
          <h2> Dominant </h2>
          {harmonicFunctionGroups.D.map((el) => {
            return <p key={el}>{el}</p>;
          })}*/}
        </div>
      </main>
    </div>
      </KeyProvider>
  );
};

export default Home;
