import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Background } from "../atoms/Background";
import { Canvas } from "@react-three/fiber";
import { Overlay } from "./Overlay";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nashville Numbers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.canvasBackgroud}>
          <Canvas
            className={styles.backgroundCanvas}
            camera={{ position: [0, 0, 1] }}
          >
            <Background />
          </Canvas>
        </div>
        <Overlay />
      </main>
    </div>
  );
};

export default Home;
